### ISSUE TITLE
Autodeploy documentation online

### ISSUE THREAD

**Issue by TimBuckers** [project-march/march-iv#167]
To keep our documentation always up to date, it should be build automatically whenever a repository gets a new push on develop.

- [x] Setup a readthedocs account that can host doxygen.

- [x] Configure git hooks to trigger a documentation deployment when all submodules update.

Checkout the following customizations

- [x] https://github.com/vovkos/doxyrest

- [x] https://github.com/foonathan/standardese

- [x] https://mcss.mosra.cz/doxygen/

**Comment by Ishadijcks** [comment]
Currently the documentation is deployed by the latest pull request in any submodule. While this is not ideal it is not a big problem with our development velocity and limited amount of branches.

I highly doubt we'll come around to fixing it this year, but I have created an issue for it anyway. #193

**Comment by Ishadijcks** [comment]
Currently the documentation is deployed by the latest pull request in any submodule. While this is not ideal it is not a big problem with our development velocity and limited amount of branches.

I highly doubt we'll come around to fixing it this year, but I have created an issue for it anyway. #
