### ISSUE TITLE
The rqt input device doesn't work with the simulation

### ISSUE THREAD

**Issue by JitskedeVries** [project-march/march-iv#227]
## Describe the bug
The rqt input device isn't able to communicate with the simulation. Since buttons on the input device are pushed, but the simulation doesn't react with a movement. The following warning is thrown. 
[WARN] [1559639523.426600]: Still waiting for action server 'march/gait/perform' to start... is it running?
However this there is a topic called march/gait/perform.

## To Reproduce
1. Go to develop of all branches
2. Launch the march_iv by ``` roslaunch march_launch march_iv.launch ```
3. Select the input device and either the rqt or the gazebo visualisation
4. Click on a button of the input device
5. See no movement and the warning

## Expected behavior
I expect that the visualization will follow the instructions given by the input device. 

## Screenshots
Here can be seen that the exoskeleton must be sitting, but he isn't.
![Screenshot from 2019-06-04 11-29-00](https://user-images.githubusercontent.com/43438024/58868144-048f8900-86bc-11e9-869f-ac57fa0af3c0.png)

## Additional context 
It might have something to do with that the rqt_input_device package is added to my workspace today.

**Comment by Ishadijcks** [comment]
This has nothing to do with the input device.
```
[WARN] [1559639523.426600]: Still waiting for action server 'march/gait/perform' to start... is it running?
```

This means the action server launched by the `march_gait_scheduler` package is not running for some reason.

Can you run it with `roslaunch march_gait_scheduler march_gait_scheduler.launch`?

I also could not reproduce this bug.
https://gfycat.com/BaggySpitefulGreyhounddog

**Comment by JitskedeVries** [comment]
Then it probably has something to do with my workspace...
