### ISSUE TITLE
For certain error types clear scheduled gait

### ISSUE THREAD

**Issue by TimBuckers** [project-march/march-iv#233]

**Comment by Olavhaasie** [comment]
@TimBuckers Could you elaborate on this issue? Is this still relevant?

**Comment by TimBuckers** [comment]
So for some errors you want to stop the current trajectory execution, this happens when the actual position is too much behind the desired. Now the system is stuck, but you still can have a scheduled gait in the gait scheduler.

And you could also have errors for which the safest way to handle is: finish current subgait, but don't executed the next scheduled gait. At least that was something we thought was nice to have.

**Comment by Olavhaasie** [comment]
Moved to Jira
