### ISSUE TITLE
Cannot use rqt input device in simulation mode

### ISSUE THREAD

**Issue by sopje** [project-march/march-iv#257]
I get the following warnings in my terminal when I press home:

[WARN] [1561996413.318289]: Still waiting for action server 'march/gait/perform' to start... is it running?
[INFO] [1561996436.421288]: Connected to action server 'march/gait/perform'.
[FATAL] [1561996436.421572]: Action server for march/gait/perform is not running.

**Comment by Ishadijcks** [comment]
Not related to the input device, this means you haven't launched the gait selection node
