### ISSUE TITLE
More software checks

### ISSUE THREAD

**Issue by JitskedeVries** [project-march/march-iv#300]
I don't know if all these things are possible to check, but here are some suggestions:
- Check on which branches the repos are on, must be either on develop or on the most recent training branch
- Check joint inside softlimits before launching the hardware interface (could save time).
- Check if the logfiles are stored on an existing location. Thus if rosbagnode which is launched in the launch file is working.

**Comment by Ishadijcks** [comment]
> Check joint inside softlimits before launching the hardware interface (could save time).

Not possible, the `hardware_interface` needs to be started before we can read joint positions
