### ISSUE TITLE
Error during airgaiting for scheduling gaits

### ISSUE THREAD

**Issue by martijnvandermarel** [project-march/march-iv#310]
> [ERROR] [1565010000.109898955]: When trying to schedule a trajectory the following error occurred: There is already a gait scheduled in the future.
> [ERROR] [1565010000.109971128]: Gait scheduling ABORTED

Gait: walk. Version: MIV_HAA.

Error occurred while airgaiting, we launched the march_launch file. The exoskeleton stopped walking.

**Comment by Ishadijcks** [comment]
Can you upload the bag file and more of the log?

**Comment by martijnvandermarel** [comment]
[_2019-08-05-14-58-27.zip](https://github.com/project-march/march-iv/files/3467784/_2019-08-05-14-58-27.zip)

more of the log in original comment

**Comment by Ishadijcks** [comment]
Previous output of the state machine is also desired, might explain something.

**Comment by martijnvandermarel** [comment]
What does that mean and how does it help with preventing it from occuring?

**Comment by Ishadijcks** [comment]
I mean more log context than just 2 lines

**Comment by martijnvandermarel** [comment]
The complete log is present in the .bag...

**Comment by Ishadijcks** [comment]
Of course, but including more context in the issue makes it easier to see what could have gone wrong without opening the bag file.

There are several prints that could explain this behavior that would save me the time of downloading and opening the bag file.

**Comment by martijnvandermarel** [comment]
I get it. There is however not much interesting stuff happening before the given lines:
> Trying to schedule subgait walk/right_swing
> WalkState: walk/right_swing
> State machine transitioning 'RIGHT SWING':'succeeded
> Trying to schedule subgait walk/left_swing
> WalkState: walk/left_swing
> State machine transitioning 'LEFT SWING':'succeeded
> Trying to schedule subgait walk/right_swing
> When trying to schedule a trajectory the following error occurred: There is already a gait scheduled in the future.
> Gait scheduling ABORTED

**Comment by Ishadijcks** [comment]
Hmm well that is unfortunate, @TimBuckers is working on it and it seems fixable :)

**Comment by TimBuckers** [comment]
Same: https://github.com/project-march/march-iv/issues/323
