### ISSUE TITLE
Gait 'succeeded' when not actually succeeded due to controller joint mismatch

### ISSUE THREAD

**Issue by martijnvandermarel** [project-march/march-iv#311]
When a mismatch is present between the joints defined in controllers.yaml and those in the urdf and a gait is played (in this case homing stand), the gait 'succeeds' and the state machine transitions (in our case to standing) even though the exoskeleton hasn't physically moved

![Screenshot from 2019-08-05 15-38-22](https://user-images.githubusercontent.com/23376251/62468985-93418480-b797-11e9-8f68-b4aee01ae600.png)

bag file:
[_2019-08-05-15-36-55.zip](https://github.com/project-march/march-iv/files/3467827/_2019-08-05-15-36-55.zip)

**Comment by Ishadijcks** [comment]
Did this occur naturally or did you force this with manual publishing somehow?

**Comment by martijnvandermarel** [comment]
Normal operation (apart from the controller mismatch of course)

**Comment by Ishadijcks** [comment]
Running with all joints? What did you expect to happend?

**Comment by martijnvandermarel** [comment]
Yes, 8 joints in urdf, 6 in controllers.yaml. Expected would be imo either a fatal error or a 'gait failed' message with the state machine staying in unknown state. It is unsafe to continue operation when the state machine is in a different state than the actual exoskeleton

**Comment by TimBuckers** [comment]
https://github.com/project-march/march-iv/pull/314 @martijnvandermarel
