### ISSUE TITLE
Gait scheduler aborted already scheduled gait in the future

### ISSUE THREAD

**Issue by Ishadijcks** [project-march/march-iv#323]
During walking we got the following error:

![image](https://user-images.githubusercontent.com/9715314/62832899-00409880-bc36-11e9-940c-4e7c1a4f7843.png)

The state machine responded properly by going to the unknown state and halting the movement at the end of the swing. The emergency button was pressed.

Bag file:

[_2019-08-11-12-31-25.bag.zip](https://github.com/project-march/march-iv/files/3489873/_2019-08-11-12-31-25.bag.zip)

**Comment by TimBuckers** [comment]
[console_logs.zip](https://github.com/project-march/march-iv/files/3494224/console_logs.zip)

**Comment by TimBuckers** [comment]
fixed in this PR https://github.com/project-march/march-iv/pull/325
